export enum ResponseCode {
  // 공통 성공
  SUCCESS = 'SUCCESS',

  // 공통 에러
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // 크롤러
  CRAWL_FAILED = 'CRAWL_FAILED',
  INVALID_CRAWL_URL = 'INVALID_CRAWL_URL',
  CRAWL_TARGET_NOT_FOUND = 'CRAWL_TARGET_NOT_FOUND',
  CRAWL_TARGET_UNAVAILABLE = 'CRAWL_TARGET_UNAVAILABLE',

  // 모델 라우터 — ModelRouterErrorCode 와 1:1 동기화 (AllExceptionsFilter 가 도메인 코드를 이 enum 에서 매칭)
  UNKNOWN_AGENT_TYPE = 'UNKNOWN_AGENT_TYPE',
  MODEL_PROVIDER_NOT_AVAILABLE = 'MODEL_PROVIDER_NOT_AVAILABLE',
  MODEL_COMPLETION_FAILED = 'MODEL_COMPLETION_FAILED',

  // Paper Recommend — PaperRecommendationErrorCode 와 1:1 동기화
  PAPER_RECOMMEND_INVALID_MODEL_OUTPUT = 'PAPER_RECOMMEND_INVALID_MODEL_OUTPUT',

  // PM Agent — PmAgentErrorCode 와 1:1 동기화
  PM_AGENT_EMPTY_TASKS_INPUT = 'PM_AGENT_EMPTY_TASKS_INPUT',
  PM_AGENT_INVALID_MODEL_OUTPUT = 'PM_AGENT_INVALID_MODEL_OUTPUT',
  PM_AGENT_NO_RECENT_PLAN = 'PM_AGENT_NO_RECENT_PLAN',
  PM_AGENT_NO_WRITE_BACK_CANDIDATES = 'PM_AGENT_NO_WRITE_BACK_CANDIDATES',

  // Work Reviewer — WorkReviewerErrorCode 와 1:1 동기화
  WORK_REVIEWER_EMPTY_WORK_INPUT = 'WORK_REVIEWER_EMPTY_WORK_INPUT',
  WORK_REVIEWER_INVALID_MODEL_OUTPUT = 'WORK_REVIEWER_INVALID_MODEL_OUTPUT',

  // Video Watch — VideoWatchErrorCode 와 1:1 동기화
  NO_YOUTUBE_URL = 'NO_YOUTUBE_URL',
  WATCH_NOT_CONFIGURED = 'WATCH_NOT_CONFIGURED',
  WATCH_FAILED = 'WATCH_FAILED',
  WATCH_TIMEOUT = 'WATCH_TIMEOUT',
  INVALID_WATCH_REPORT = 'INVALID_WATCH_REPORT',
  INVALID_MODEL_OUTPUT = 'INVALID_MODEL_OUTPUT',

  // Code Reviewer — CodeReviewerErrorCode 와 1:1 동기화
  CODE_REVIEWER_INVALID_PR_REFERENCE = 'CODE_REVIEWER_INVALID_PR_REFERENCE',
  CODE_REVIEWER_AMBIGUOUS_PR_REFERENCE = 'CODE_REVIEWER_AMBIGUOUS_PR_REFERENCE',
  CODE_REVIEWER_INVALID_MODEL_OUTPUT = 'CODE_REVIEWER_INVALID_MODEL_OUTPUT',
  CODE_REVIEWER_DIFF_TOO_LARGE = 'CODE_REVIEWER_DIFF_TOO_LARGE',
  NO_OPEN_PR_FOUND = 'NO_OPEN_PR_FOUND',

  // Impact Reporter — ImpactReporterErrorCode 와 1:1 동기화
  IMPACT_REPORTER_EMPTY_SUBJECT = 'IMPACT_REPORTER_EMPTY_SUBJECT',
  IMPACT_REPORTER_INVALID_MODEL_OUTPUT = 'IMPACT_REPORTER_INVALID_MODEL_OUTPUT',
  IMPACT_REPORTER_RECENT_MODE_ENV_MISSING = 'IMPACT_REPORTER_RECENT_MODE_ENV_MISSING',
  IMPACT_REPORTER_RECENT_MODE_NO_RESULTS = 'IMPACT_REPORTER_RECENT_MODE_NO_RESULTS',

  // PO Shadow — PoShadowErrorCode 와 1:1 동기화
  PO_SHADOW_NO_RECENT_PLAN = 'PO_SHADOW_NO_RECENT_PLAN',
  PO_SHADOW_STALE_PLAN = 'PO_SHADOW_STALE_PLAN',
  PO_SHADOW_INVALID_MODEL_OUTPUT = 'PO_SHADOW_INVALID_MODEL_OUTPUT',
  PO_SHADOW_PRODUCT_GOAL_REJECTED = 'PO_SHADOW_PRODUCT_GOAL_REJECTED',
  PO_SHADOW_INVALID_PRODUCT_GOAL_PAYLOAD = 'PO_SHADOW_INVALID_PRODUCT_GOAL_PAYLOAD',

  // Vacation — VacationErrorCode 와 1:1 동기화
  VACATION_HIRE_DATE_NOT_CONFIGURED = 'VACATION_HIRE_DATE_NOT_CONFIGURED',
  VACATION_INVALID_DATE_RANGE = 'VACATION_INVALID_DATE_RANGE',
  VACATION_INVALID_COMMAND = 'VACATION_INVALID_COMMAND',
  VACATION_USAGE_NOT_FOUND = 'VACATION_USAGE_NOT_FOUND',
  VACATION_NL_PARSE_FAILED = 'VACATION_NL_PARSE_FAILED',

  // GitHub 커넥터 — GithubErrorCode 와 1:1 동기화
  GITHUB_TOKEN_NOT_CONFIGURED = 'GITHUB_TOKEN_NOT_CONFIGURED',
  GITHUB_REQUEST_FAILED = 'GITHUB_REQUEST_FAILED',

  // Slack collector — SlackCollectorErrorCode 와 1:1 동기화
  SLACK_COLLECTOR_TOKEN_NOT_CONFIGURED = 'SLACK_COLLECTOR_TOKEN_NOT_CONFIGURED',
  SLACK_COLLECTOR_REQUEST_FAILED = 'SLACK_COLLECTOR_REQUEST_FAILED',

  // Notion 커넥터 — NotionErrorCode 와 1:1 동기화
  NOTION_TOKEN_NOT_CONFIGURED = 'NOTION_TOKEN_NOT_CONFIGURED',
  NOTION_REQUEST_FAILED = 'NOTION_REQUEST_FAILED',

  // BLOG Agent — BlogErrorCode 와 1:1 동기화
  BLOG_EMPTY_REQUEST = 'BLOG_EMPTY_REQUEST',
  BLOG_HERMES_SPAWN_FAILED = 'BLOG_HERMES_SPAWN_FAILED',
  BLOG_HERMES_TIMEOUT = 'BLOG_HERMES_TIMEOUT',
  BLOG_HERMES_NONZERO_EXIT = 'BLOG_HERMES_NONZERO_EXIT',
  BLOG_NOTION_URL_NOT_FOUND = 'BLOG_NOTION_URL_NOT_FOUND',
  BLOG_PUBLISH_CONFIG_REQUIRED = 'BLOG_PUBLISH_CONFIG_REQUIRED',
  BLOG_DRAFT_NOT_FOUND = 'BLOG_DRAFT_NOT_FOUND',
  BLOG_EMPTY_DRAFT_BODY = 'BLOG_EMPTY_DRAFT_BODY',
  BLOG_ANONYMIZE_PARSE_FAILED = 'BLOG_ANONYMIZE_PARSE_FAILED',
  BLOG_EDIT_PARSE_FAILED = 'BLOG_EDIT_PARSE_FAILED',
  BLOG_EDIT_TOO_SHORT = 'BLOG_EDIT_TOO_SHORT',
  BLOG_EDIT_CODE_CHANGED = 'BLOG_EDIT_CODE_CHANGED',
  BLOG_EDIT_QUOTES_WIPED = 'BLOG_EDIT_QUOTES_WIPED',
  BLOG_INVALID_PUBLISH_DATE = 'BLOG_INVALID_PUBLISH_DATE',

  // Career Mate — CareerMateErrorCode 와 1:1 동기화
  CAREER_MATE_NL_PARSE_FAILED = 'CAREER_MATE_NL_PARSE_FAILED',
  CAREER_MATE_NO_EVIDENCE = 'CAREER_MATE_NO_EVIDENCE',
  CAREER_MATE_INVALID_MODEL_OUTPUT = 'CAREER_MATE_INVALID_MODEL_OUTPUT',
  CAREER_MATE_CONFIG_MISSING = 'CAREER_MATE_CONFIG_MISSING',
  CAREER_MATE_JD_EMPTY = 'CAREER_MATE_JD_EMPTY',
  CAREER_MATE_INVALID_PR_REFERENCE = 'CAREER_MATE_INVALID_PR_REFERENCE',

  // Job Application — JobApplicationErrorCode 와 1:1 동기화
  JOB_APPLICATION_NL_PARSE_FAILED = 'JOB_APPLICATION_NL_PARSE_FAILED',
  JOB_APPLICATION_MISSING_FIELDS = 'JOB_APPLICATION_MISSING_FIELDS',
  JOB_APPLICATION_NOT_FOUND = 'JOB_APPLICATION_NOT_FOUND',
  JOB_APPLICATION_INVALID_STATUS = 'JOB_APPLICATION_INVALID_STATUS',

  // Run Replay — ReplayRejectionCode 와 1:1 동기화
  RUN_REPLAY_NOT_FOUND = 'RUN_REPLAY_NOT_FOUND',
  RUN_REPLAY_INVALID_SNAPSHOT = 'RUN_REPLAY_INVALID_SNAPSHOT',
  RUN_REPLAY_FORBIDDEN = 'RUN_REPLAY_FORBIDDEN',
  RUN_REPLAY_NOT_SUPPORTED = 'RUN_REPLAY_NOT_SUPPORTED',
  RUN_REPLAY_NOT_REPRODUCIBLE = 'RUN_REPLAY_NOT_REPRODUCIBLE',
  RUN_REPLAY_UNKNOWN_AGENT_TYPE = 'RUN_REPLAY_UNKNOWN_AGENT_TYPE',
  RUN_REPLAY_IN_FLIGHT = 'RUN_REPLAY_IN_FLIGHT',

  // CEO — CeoErrorCode 와 1:1 동기화
  NO_PO_EVAL_RUN = 'NO_PO_EVAL_RUN',

  // PO Eval — PoEvalErrorCode 와 1:1 동기화
  NO_SUB_AGENT_RUNS = 'NO_SUB_AGENT_RUNS',
  // CEO 와 PO Eval 의 LLM 출력 파싱 오류가 의도적으로 공유하는 response code.
  // 도메인 값이 agent_run.errorCode 로 저장되므로 접두를 붙여 나누지 않았다.
  PARSE_FAILED = 'PARSE_FAILED',

  // CTO — CtoErrorCode 와 1:1 동기화
  INVALID_STUDY_VERDICT = 'INVALID_STUDY_VERDICT',

  // Preview Gate — PreviewActionErrorCode 와 1:1 동기화
  PREVIEW_NOT_FOUND = 'PREVIEW_NOT_FOUND',
  PREVIEW_ALREADY_RESOLVED = 'PREVIEW_ALREADY_RESOLVED',
  PREVIEW_EXPIRED = 'PREVIEW_EXPIRED',
  PREVIEW_WRONG_OWNER = 'PREVIEW_WRONG_OWNER',
  PREVIEW_NO_APPLIER_FOR_KIND = 'PREVIEW_NO_APPLIER_FOR_KIND',
  PREVIEW_ALREADY_APPLYING = 'PREVIEW_ALREADY_APPLYING',

  // Router — RouterErrorCode 와 1:1 동기화
  INTENT_HINT_REQUIRED = 'INTENT_HINT_REQUIRED',
  UNSUPPORTED_AGENT_TYPE = 'UNSUPPORTED_AGENT_TYPE',
  CYCLE_DETECTED = 'CYCLE_DETECTED',
  DEPTH_EXCEEDED = 'DEPTH_EXCEEDED',
  INTENT_CLASSIFY_FAILED = 'INTENT_CLASSIFY_FAILED',
  DISPATCHER_REGISTRY_INVALID = 'DISPATCHER_REGISTRY_INVALID',

  // Study Brief — StudyBriefErrorCode 와 1:1 동기화
  INVALID_RESEARCH_OUTPUT = 'INVALID_RESEARCH_OUTPUT',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  INVALID_DEEPDIVE_OUTPUT = 'INVALID_DEEPDIVE_OUTPUT',
  INVALID_APPLICABILITY_OUTPUT = 'INVALID_APPLICABILITY_OUTPUT',

  // Subconscious — SubconsciousErrorCode 와 1:1 동기화
  SUBCONSCIOUS_PROPOSAL_ERROR = 'SUBCONSCIOUS_PROPOSAL_ERROR',
}
