export enum ResponseCode {
  // 공통 성공
  SUCCESS = 'SUCCESS',

  // 공통 에러
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // 크롤러
  CRAWL_FAILED = 'CRAWL_FAILED',
  INVALID_CRAWL_URL = 'INVALID_CRAWL_URL',
  CRAWL_TARGET_NOT_FOUND = 'CRAWL_TARGET_NOT_FOUND',
  CRAWL_TARGET_UNAVAILABLE = 'CRAWL_TARGET_UNAVAILABLE',

  // 모델 라우터 — ModelRouterErrorCode 와 1:1 동기화 (AllExceptionsFilter 가 도메인 코드를 이 enum 에서 매칭)
  UNKNOWN_AGENT_TYPE = 'UNKNOWN_AGENT_TYPE',
  MODEL_PROVIDER_NOT_AVAILABLE = 'MODEL_PROVIDER_NOT_AVAILABLE',
  MODEL_COMPLETION_FAILED = 'MODEL_COMPLETION_FAILED',

  // PM Agent — PmAgentErrorCode 와 1:1 동기화
  PM_AGENT_EMPTY_TASKS_INPUT = 'PM_AGENT_EMPTY_TASKS_INPUT',
  PM_AGENT_INVALID_MODEL_OUTPUT = 'PM_AGENT_INVALID_MODEL_OUTPUT',

  // Work Reviewer — WorkReviewerErrorCode 와 1:1 동기화
  WORK_REVIEWER_EMPTY_WORK_INPUT = 'WORK_REVIEWER_EMPTY_WORK_INPUT',
  WORK_REVIEWER_INVALID_MODEL_OUTPUT = 'WORK_REVIEWER_INVALID_MODEL_OUTPUT',

  // Code Reviewer — CodeReviewerErrorCode 와 1:1 동기화
  CODE_REVIEWER_INVALID_PR_REFERENCE = 'CODE_REVIEWER_INVALID_PR_REFERENCE',
  CODE_REVIEWER_INVALID_MODEL_OUTPUT = 'CODE_REVIEWER_INVALID_MODEL_OUTPUT',

  // Impact Reporter — ImpactReporterErrorCode 와 1:1 동기화
  IMPACT_REPORTER_EMPTY_SUBJECT = 'IMPACT_REPORTER_EMPTY_SUBJECT',
  IMPACT_REPORTER_INVALID_MODEL_OUTPUT = 'IMPACT_REPORTER_INVALID_MODEL_OUTPUT',

  // PO Shadow — PoShadowErrorCode 와 1:1 동기화
  PO_SHADOW_NO_RECENT_PLAN = 'PO_SHADOW_NO_RECENT_PLAN',
  PO_SHADOW_INVALID_MODEL_OUTPUT = 'PO_SHADOW_INVALID_MODEL_OUTPUT',

  // Vacation — VacationErrorCode 와 1:1 동기화
  VACATION_HIRE_DATE_NOT_CONFIGURED = 'VACATION_HIRE_DATE_NOT_CONFIGURED',
  VACATION_INVALID_DATE_RANGE = 'VACATION_INVALID_DATE_RANGE',
  VACATION_INVALID_COMMAND = 'VACATION_INVALID_COMMAND',
  VACATION_USAGE_NOT_FOUND = 'VACATION_USAGE_NOT_FOUND',
  VACATION_NL_PARSE_FAILED = 'VACATION_NL_PARSE_FAILED',

  // BE Agent — BeAgentErrorCode 와 1:1 동기화
  BE_AGENT_EMPTY_SUBJECT = 'BE_AGENT_EMPTY_SUBJECT',
  BE_AGENT_INVALID_MODEL_OUTPUT = 'BE_AGENT_INVALID_MODEL_OUTPUT',
  BE_AGENT_PR_GROUNDING_REQUIRED = 'BE_AGENT_PR_GROUNDING_REQUIRED',

  // GitHub 커넥터 — GithubErrorCode 와 1:1 동기화
  GITHUB_TOKEN_NOT_CONFIGURED = 'GITHUB_TOKEN_NOT_CONFIGURED',
  GITHUB_REQUEST_FAILED = 'GITHUB_REQUEST_FAILED',

  // Slack collector — SlackCollectorErrorCode 와 1:1 동기화
  SLACK_COLLECTOR_TOKEN_NOT_CONFIGURED = 'SLACK_COLLECTOR_TOKEN_NOT_CONFIGURED',
  SLACK_COLLECTOR_REQUEST_FAILED = 'SLACK_COLLECTOR_REQUEST_FAILED',

  // Notion 커넥터 — NotionErrorCode 와 1:1 동기화
  NOTION_TOKEN_NOT_CONFIGURED = 'NOTION_TOKEN_NOT_CONFIGURED',
  NOTION_REQUEST_FAILED = 'NOTION_REQUEST_FAILED',

  // Issue Labeler — IssueLabelerErrorCode 와 1:1 동기화
  ISSUE_LABELER_EMPTY_INPUT = 'ISSUE_LABELER_EMPTY_INPUT',
  ISSUE_LABELER_INVALID_MODEL_OUTPUT = 'ISSUE_LABELER_INVALID_MODEL_OUTPUT',
  ISSUE_LABELER_NO_REPO_LABELS = 'ISSUE_LABELER_NO_REPO_LABELS',

  // BLOG Agent — BlogErrorCode 와 1:1 동기화
  BLOG_EMPTY_REQUEST = 'BLOG_EMPTY_REQUEST',
  BLOG_HERMES_SPAWN_FAILED = 'BLOG_HERMES_SPAWN_FAILED',
  BLOG_HERMES_TIMEOUT = 'BLOG_HERMES_TIMEOUT',
  BLOG_HERMES_NONZERO_EXIT = 'BLOG_HERMES_NONZERO_EXIT',
  BLOG_NOTION_URL_NOT_FOUND = 'BLOG_NOTION_URL_NOT_FOUND',

  // Career Mate — CareerMateErrorCode 와 1:1 동기화
  CAREER_MATE_NL_PARSE_FAILED = 'CAREER_MATE_NL_PARSE_FAILED',
  CAREER_MATE_NO_EVIDENCE = 'CAREER_MATE_NO_EVIDENCE',
  CAREER_MATE_INVALID_MODEL_OUTPUT = 'CAREER_MATE_INVALID_MODEL_OUTPUT',
  CAREER_MATE_CONFIG_MISSING = 'CAREER_MATE_CONFIG_MISSING',
  CAREER_MATE_JD_EMPTY = 'CAREER_MATE_JD_EMPTY',

  // Job Application — JobApplicationErrorCode 와 1:1 동기화
  JOB_APPLICATION_NL_PARSE_FAILED = 'JOB_APPLICATION_NL_PARSE_FAILED',
  JOB_APPLICATION_MISSING_FIELDS = 'JOB_APPLICATION_MISSING_FIELDS',
  JOB_APPLICATION_NOT_FOUND = 'JOB_APPLICATION_NOT_FOUND',
  JOB_APPLICATION_INVALID_STATUS = 'JOB_APPLICATION_INVALID_STATUS',
}
