export enum ResponseCode {
  // 공통 성공
  SUCCESS = 'SUCCESS',

  // 공통 에러
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // 크롤러
  CRAWL_FAILED = 'CRAWL_FAILED',
  INVALID_CRAWL_URL = 'INVALID_CRAWL_URL',
  CRAWL_TARGET_NOT_FOUND = 'CRAWL_TARGET_NOT_FOUND',
  CRAWL_TARGET_UNAVAILABLE = 'CRAWL_TARGET_UNAVAILABLE',

  // 모델 라우터 — ModelRouterErrorCode 와 1:1 동기화 (AllExceptionsFilter 가 도메인 코드를 이 enum 에서 매칭)
  UNKNOWN_AGENT_TYPE = 'UNKNOWN_AGENT_TYPE',
  MODEL_PROVIDER_NOT_AVAILABLE = 'MODEL_PROVIDER_NOT_AVAILABLE',
  MODEL_COMPLETION_FAILED = 'MODEL_COMPLETION_FAILED',

  // PM Agent — PmAgentErrorCode 와 1:1 동기화
  PM_AGENT_EMPTY_TASKS_INPUT = 'PM_AGENT_EMPTY_TASKS_INPUT',
  PM_AGENT_INVALID_MODEL_OUTPUT = 'PM_AGENT_INVALID_MODEL_OUTPUT',
}
