export enum CodeReviewerErrorCode {
  INVALID_PR_REFERENCE = 'CODE_REVIEWER_INVALID_PR_REFERENCE',
  INVALID_MODEL_OUTPUT = 'CODE_REVIEWER_INVALID_MODEL_OUTPUT',
  NO_OPEN_PR_FOUND = 'NO_OPEN_PR_FOUND',
}
