export enum BeDiffGeneratorErrorCode {
  EMPTY_PLAN = 'BE_DIFF_GENERATOR_EMPTY_PLAN',
  INVALID_MODEL_OUTPUT = 'BE_DIFF_GENERATOR_INVALID_MODEL_OUTPUT',
  INVALID_DIFF_FORMAT = 'BE_DIFF_GENERATOR_INVALID_DIFF_FORMAT',
}
