export enum JobApplicationErrorCode {
  NL_PARSE_FAILED = 'JOB_APPLICATION_NL_PARSE_FAILED',
  MISSING_FIELDS = 'JOB_APPLICATION_MISSING_FIELDS',
  NOT_FOUND = 'JOB_APPLICATION_NOT_FOUND',
  INVALID_STATUS = 'JOB_APPLICATION_INVALID_STATUS',
}
