export enum VideoWatchErrorCode {
  NO_YOUTUBE_URL = 'NO_YOUTUBE_URL',
  WATCH_NOT_CONFIGURED = 'WATCH_NOT_CONFIGURED',
  WATCH_FAILED = 'WATCH_FAILED',
  WATCH_TIMEOUT = 'WATCH_TIMEOUT',
  INVALID_WATCH_REPORT = 'INVALID_WATCH_REPORT',
  INVALID_MODEL_OUTPUT = 'INVALID_MODEL_OUTPUT',
}
