export enum ImpactReporterErrorCode {
  EMPTY_SUBJECT = 'IMPACT_REPORTER_EMPTY_SUBJECT',
  INVALID_MODEL_OUTPUT = 'IMPACT_REPORTER_INVALID_MODEL_OUTPUT',
  // `/impact-report --recent <N>d` 모드 호출 시 env (IMPACT_REPORT_GITHUB_AUTHOR /
  // IMPACT_REPORT_GITHUB_REPO) 가 누락된 경우.
  RECENT_MODE_ENV_MISSING = 'IMPACT_REPORTER_RECENT_MODE_ENV_MISSING',
  // recent mode 에서 GitHub 검색 결과가 0건인 경우 — 사용자가 그 기간에 머지한 PR 없음.
  RECENT_MODE_NO_RESULTS = 'IMPACT_REPORTER_RECENT_MODE_NO_RESULTS',
}
