export enum BeTestErrorCode {
  EMPTY_PATH = 'EMPTY_PATH',
  INVALID_PATH = 'INVALID_PATH',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  PARSE_FAILED = 'PARSE_FAILED',
  SANDBOX_VALIDATION_FAILED = 'SANDBOX_VALIDATION_FAILED',
  SELF_CORRECTION_EXHAUSTED = 'SELF_CORRECTION_EXHAUSTED',
}
