/**
 * sync-docs — docs-as-code 생성기 + 드리프트 게이트
 *
 * 코드의 단일 소스(SoT)에서 머신-정확한 레퍼런스 카탈로그를 생성한다.
 * sbe-slack-bot 의 sync-docs(.cjs) 패턴을 이 레포에 맞게 이식한 것.
 *
 * 생성 대상 (둘 다 전체가 생성물 — 수동 편집 금지):
 *   - docs/agent-catalog.md  ← AGENT_REGISTRY + AGENT_TO_PROVIDER (둘 다 import — 타입이 보장)
 *   - docs/env-catalog.md    ← src/config/app.config.ts (텍스트 파싱: 이름/필수/설명/그룹)
 *
 * env 만 텍스트 파싱인 이유: 설명이 주석에 있어 import 로는 얻을 수 없다. 텍스트 파싱은
 * SoT 서식이 바뀌면 조용히 어긋나므로 assertEnvEntries() 가 최소 계약을 강제한다
 * (--check 는 "렌더 결과 == 파일" 만 보기 때문에 파서가 망가져도 green 이 될 수 있다).
 *
 * 손으로 큐레이션된 README 는 일부러 덮지 않는다(발췌·그룹핑이 생성 덤프보다 낫다).
 * README 는 위 두 카탈로그를 링크로 가리킨다.
 *
 * 모드:
 *   ts-node scripts/sync-docs.ts           # 카탈로그 재생성(쓰기)  → pnpm docs:sync
 *   ts-node scripts/sync-docs.ts --check   # 드리프트 시 exit 1     → pnpm docs:check
 *
 * `.env.example` 동기는 본 생성기 범위 밖 — scripts/check-env-sync.cjs(pnpm check:env) 가 담당.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { getMetadataStorage } from 'class-validator';

import { AGENT_CONTRACTS } from '../src/agent-registry/agent-contract';
import { AGENT_REGISTRY } from '../src/agent-registry/agent-registry';
import { EnvironmentVariables } from '../src/config/app.config';
import { AGENT_TO_PROVIDER } from '../src/model-router/domain/agent-provider.map';

const REPO_ROOT = resolve(__dirname, '..');
const APP_CONFIG_PATH = join(REPO_ROOT, 'src', 'config', 'app.config.ts');
const AGENT_CATALOG_PATH = join(REPO_ROOT, 'docs', 'agent-catalog.md');
const ENV_CATALOG_PATH = join(REPO_ROOT, 'docs', 'env-catalog.md');

/** 오피스 화면이 사람에게 붙이는 한글 직책표(agentType → 이름표). */
const CONSOLE_ROLE_PATH = join(
  REPO_ROOT,
  'clients/idaeri-console/Sources/ConsoleCore/AgentRole.swift',
);

/** 오피스 자리 배치 검사가 쓰는 인원 표본. 사규의 실제 인원·부서를 재현해야 한다. */
const CONSOLE_SAMPLE_PATH = join(
  REPO_ROOT,
  'clients/idaeri-console/Sources/ConsoleCoreTests/OfficeFloorPlanTests.swift',
);

const GENERATED_BANNER =
  '<!-- AUTO-GENERATED by scripts/sync-docs.ts — 직접 편집하지 마세요. `pnpm docs:sync` 로 갱신. -->';

/** 설명이 한 문장으로 안 끝날 때 이어붙일 최대 주석 줄 수. */
const MAX_DESCRIPTION_LINES = 3;

/** 이 길이를 넘으면 첫 문장만 남긴다(표 셀이라 문단 전체는 못 담는다). */
const MAX_DESCRIPTION_LENGTH = 160;

/** 필수로 파싱돼야 하는 앵커 키 — required 판정이 통째로 뒤집히는 회귀 탐지용. */
const REQUIRED_ANCHOR_KEYS = ['DATABASE_URL', 'REDIS_HOST'] as const;

// ──────────────────────────── 파서 ────────────────────────────

interface EnvEntry {
  name: string;
  required: boolean;
  description: string;
}

/**
 * 표 셀에 담을 길이로 다듬는다. 상한을 넘을 때만 첫 문장을 남긴다.
 * 문장 끝 판정이 "마침표 뒤가 공백이거나 문자열 끝" 인 것은 `pull_request.opened` 나
 * `(\`U...\`)` 같은 문장 중간 마침표를 문장 끝으로 오인하지 않기 위해서다.
 */
function clampDescription(text: string): string {
  if (text.length <= MAX_DESCRIPTION_LENGTH) {
    return text;
  }
  const firstSentence = text.match(/^[\s\S]*?[.。!?](?=\s|$)/u);
  return firstSentence ? firstSentence[0].trim() : text;
}

/**
 * 주석 블록 → 설명.
 * 첫 줄만 쓰면 "…user.login 과" 처럼 중간에서 잘린 설명이 실리므로, 문장이 완결될 때까지
 * 줄을 이어붙인 뒤 길이를 다듬는다.
 */
function toDescription(commentBuffer: readonly string[]): string {
  let description = '';
  for (const line of commentBuffer.slice(0, MAX_DESCRIPTION_LINES)) {
    description = description ? `${description} ${line}` : line;
    if (/[.。!?]$/u.test(description)) {
      break;
    }
  }
  return clampDescription(description);
}

/**
 * app.config.ts → env 항목.
 * `@IsOptional` 유무로 required 판정, 속성 직전 contiguous `//` 블록을 설명으로.
 *
 * 주석 안의 `// - KEY: 설명` 줄은 그 키 전용 설명으로 따로 수집한다(블록 설명보다 우선).
 * 한 주석이 여러 키를 설명하는 구간(RESUME_CALIBRATION_*, JOB_APPLICATION_NUDGE_* 등)에서
 * 블록 첫 항목만 설명을 갖고 나머지가 빈칸이 되는 문제를 이 규칙이 해소한다.
 */
function parseEnvEntries(): EnvEntry[] {
  const lines = readFileSync(APP_CONFIG_PATH, 'utf8').split(/\r?\n/u);
  const entries: EnvEntry[] = [];
  const keyedDescriptions = new Map<string, string>();
  let optionalFlag = false;
  let commentBuffer: string[] = [];
  let pendingKeyedName: string | null = null;

  for (const raw of lines) {
    const line = raw.trim();

    if (line.startsWith('//')) {
      const comment = line.replace(/^\/\/\s?/u, '').trim();
      const keyed = comment.match(/^-\s*([A-Z][A-Z0-9_]+)\s*:\s*(.+)$/u);
      if (keyed) {
        keyedDescriptions.set(keyed[1], keyed[2].trim());
        pendingKeyedName = keyed[1];
        continue;
      }
      // `//   …` 처럼 한 칸 넘게 들여쓴 줄은 직전 `- KEY:` 설명이 줄바꿈된 것.
      if (pendingKeyedName !== null && /^\/\/\s{2,}/u.test(line)) {
        const written = keyedDescriptions.get(pendingKeyedName) ?? '';
        keyedDescriptions.set(pendingKeyedName, `${written} ${comment}`.trim());
        continue;
      }
      pendingKeyedName = null;
      // `====== 섹션 이름 ======` 배너는 설명이 아니다.
      if (/^={3,}/u.test(comment)) {
        continue;
      }
      commentBuffer.push(comment);
      continue;
    }
    pendingKeyedName = null;
    if (line.startsWith('@IsOptional')) {
      optionalFlag = true;
      continue;
    }
    if (line.startsWith('@')) {
      // 다른 데코레이터 — 주석 버퍼는 유지(설명은 데코레이터 위에 있음).
      continue;
    }

    const propertyMatch = raw.match(/^\s+([A-Z][A-Z0-9_]+)[?!]?\s*:/u);
    if (propertyMatch) {
      entries.push({
        name: propertyMatch[1],
        required: !optionalFlag,
        description: toDescription(commentBuffer),
      });
      optionalFlag = false;
      commentBuffer = [];
      continue;
    }

    // 빈 줄 = 속성 블록 경계 → stale 주석 버퍼 리셋. 데코레이터 인자의 multi-line
    // 본문(예: @Matches({ message: ... }))은 비-빈 줄이라 리셋하지 않아, 주석이 속성까지 살아남는다.
    if (line.length === 0) {
      commentBuffer = [];
    }
  }

  return entries.map((entry) => {
    const keyed = keyedDescriptions.get(entry.name);
    const description = keyed ? clampDescription(keyed) : entry.description;
    return {
      ...entry,
      // `// KEY: 설명` 형식 주석은 표에서 키가 두 번 나오므로 자기 이름 접두사를 벗긴다.
      description: description.replace(
        new RegExp(`^${entry.name}\\s*:\\s*`, 'u'),
        '',
      ),
    };
  });
}

/**
 * class-validator 메타데이터에 등록된 env 속성 이름.
 * 텍스트 파싱과 독립된 진짜 SoT — 데코레이터가 런타임에 실제로 등록한 것만 나온다.
 */
function readDeclaredEnvNames(): Set<string> {
  const metadatas = getMetadataStorage().getTargetValidationMetadatas(
    EnvironmentVariables,
    '',
    false,
    false,
  );
  return new Set(metadatas.map((metadata) => metadata.propertyName));
}

/**
 * 파서 계약 검증.
 * `--check` 는 "렌더 결과 == 파일 내용" 만 비교하므로, 파서가 SoT 를 잘못 읽어도
 * `docs:sync` 한 번이면 그 잘못된 결과가 정본이 되고 게이트는 통과한다.
 * 파싱 실패는 조용한 빈칸이 아니라 게이트 실패여야 한다.
 *
 * 개수 하한 같은 느슨한 기준이 아니라 선언된 이름 집합과 정확히 대조한다 —
 * 하한만 보면 107개 중 일부만 사라진 부분 누락이 그대로 통과한다.
 */
function assertEnvEntries(entries: readonly EnvEntry[]): void {
  const declared = readDeclaredEnvNames();
  const parsed = new Set(entries.map((entry) => entry.name));
  const missing = [...declared].filter((name) => !parsed.has(name));
  const unexpected = [...parsed].filter((name) => !declared.has(name));
  if (missing.length > 0 || unexpected.length > 0) {
    throw new Error(
      `[sync-docs] 파싱 결과가 EnvironmentVariables 선언과 다릅니다(선언 ${declared.size} / 파싱 ${parsed.size}).\n` +
        `  누락: ${missing.join(', ') || '없음'}\n` +
        `  초과: ${unexpected.join(', ') || '없음'}\n` +
        '  app.config.ts 의 속성 선언 서식이 바뀌었는지 확인하세요.',
    );
  }

  const duplicated = entries
    .map((entry) => entry.name)
    .filter((name, index, names) => names.indexOf(name) !== index);
  if (duplicated.length > 0) {
    throw new Error(
      `[sync-docs] env 키가 중복 파싱됐습니다: ${[...new Set(duplicated)].join(', ')}`,
    );
  }

  for (const anchor of REQUIRED_ANCHOR_KEYS) {
    const found = entries.find((entry) => entry.name === anchor);
    if (!found) {
      throw new Error(`[sync-docs] 앵커 키 ${anchor} 를 못 찾았습니다.`);
    }
    if (!found.required) {
      throw new Error(
        `[sync-docs] ${anchor} 가 optional 로 파싱됐습니다. @IsOptional 판정이 어긋났거나 ` +
          '실제로 필수에서 빠졌다면 REQUIRED_ANCHOR_KEYS 를 갱신하세요.',
      );
    }
  }
}

/** Swift 소스에서 줄 주석을 걷어낸다 — 주석에 적힌 예시를 실제 매핑으로 세지 않게. */
function stripSwiftLineComments(source: string): string {
  return source
    .split('\n')
    .map((line) => line.replace(/\/\/.*$/u, ''))
    .join('\n');
}

/**
 * 오피스 화면(Swift)이 사규의 사람을 전부 알고 있는지 확인한다.
 *
 * 백엔드에 에이전트를 추가해도 콘솔은 컴파일이 깨지지 않는다 — 직책이 없으면 조용히 영문
 * 표시명으로 폴백하고, 검사 표본이 예전 인원에 머물러도 자리 배치 단언은 그대로 통과한다.
 * 실제로 `PAPER_TRADE`·`PAPER_RECOMMEND` 가 그렇게 빠져, 성장 부서가 8명인데 6명으로
 * 검사되는 동안 이름표 셋이 서로를 덮고 있었다. 사람이 늘었다는 사실은 사규만 알고 있으므로
 * 여기서 잇는다.
 *
 * 부서까지 대조하는 것은 표본의 **인원수만** 맞추면 방마다 몇 명인지가 어긋나 자리 부족이
 * 다른 방에서 검사되기 때문이다.
 */
function assertConsoleAgentSync(): void {
  const declared = AGENT_REGISTRY.map((entry) => entry.agentType);

  const roleSource = stripSwiftLineComments(
    readFileSync(CONSOLE_ROLE_PATH, 'utf8'),
  );
  // `agentRoleLabel` 본문으로 잘라서 센다. 파일 전체를 훑으면 다른 switch 의 같은 case 가
  // "직책이 있다" 로 잡혀, 정작 이름표를 만드는 함수에는 없는데도 통과한다.
  const roleBodyStart = roleSource.indexOf('func agentRoleLabel');
  const roleBodyEnd = roleSource.indexOf('default:', roleBodyStart);
  if (roleBodyStart < 0 || roleBodyEnd < 0) {
    throw new Error(
      `[sync-docs] ${toRepoRelative(CONSOLE_ROLE_PATH)} 에서 agentRoleLabel 본문을 못 찾았습니다.\n` +
        '  함수 이름이나 switch 서식이 바뀌었는지 확인하세요(파싱이 조용히 빈 결과를 내면 안 됩니다).',
    );
  }
  const roleBody = roleSource.slice(roleBodyStart, roleBodyEnd);
  // 반환값이 비어 있지 않은 case 만 인정한다 — 빈 이름표는 없는 것과 같다.
  // 길이·표기 규칙은 Swift 쪽 `runAgentRoleTests` 가 검사한다(CEO·CTO 는 의도적 영문).
  const labeled = new Set(
    [...roleBody.matchAll(/case "(\w+)":\s*return\s*"([^"]+)"/gu)].map(
      (match) => match[1],
    ),
  );
  const unlabeled = declared.filter((type) => !labeled.has(type));
  if (unlabeled.length > 0) {
    throw new Error(
      `[sync-docs] 오피스 한글 직책이 없는 에이전트: ${unlabeled.join(', ')}\n` +
        `  ${toRepoRelative(CONSOLE_ROLE_PATH)} 의 agentRoleLabel 에 추가하세요(이름표가 겹치지 않게 7자 이내).\n` +
        '  없으면 그 사람만 영문 표시명으로 폴백해 이름표가 뒤섞입니다.',
    );
  }

  const sampleSource = stripSwiftLineComments(
    readFileSync(CONSOLE_SAMPLE_PATH, 'utf8'),
  );
  const sampled = new Map<string, string>();
  // 같은 사람이 두 방에 적히면 Map 이 덮어써서 조용히 하나로 합쳐진다 — 파싱 단계에서 잡는다.
  const duplicated: string[] = [];
  for (const group of sampleSource.matchAll(
    /planAgents\(\s*\.(\w+),\s*\[([^\]]*)\]/gu,
  )) {
    for (const quoted of group[2].matchAll(/"(\w+)"/gu)) {
      if (sampled.has(quoted[1])) {
        duplicated.push(quoted[1]);
      }
      sampled.set(quoted[1], group[1]);
    }
  }
  // Department 의 값이 곧 Swift enum case 이름이라(`internalOps`) 그대로 견줄 수 있다.
  const declaredTypes = new Set<string>(declared);
  const missing = declared.filter((type) => !sampled.has(type));
  // **표본에만 있는 사람도 실패다.** 사규에서 에이전트를 지웠는데 표본에 남으면 유령 인원으로
  // 자리·이름표 검사가 계속 돌아, 멀쩡한 배치 변경을 막거나 실제 구성의 회귀를 놓친다.
  // 같은 파일 `assertEnvEntries` 가 누락과 초과를 함께 보는 것과 같은 이유다.
  const unexpected = [...sampled.keys()].filter(
    (type) => !declaredTypes.has(type),
  );
  const misplaced = declared
    .filter((type) => sampled.has(type))
    .filter((type) => sampled.get(type) !== AGENT_CONTRACTS[type].department)
    .map(
      (type) =>
        `${type}(표본 ${sampled.get(type)} ≠ 사규 ${AGENT_CONTRACTS[type].department})`,
    );
  if (
    missing.length > 0 ||
    unexpected.length > 0 ||
    misplaced.length > 0 ||
    duplicated.length > 0
  ) {
    throw new Error(
      `[sync-docs] 오피스 자리 검사 표본이 사규와 다릅니다(사규 ${declared.length}명 / 표본 ${sampled.size}명).\n` +
        `  누락: ${missing.join(', ') || '없음'}\n` +
        `  초과: ${unexpected.join(', ') || '없음'}\n` +
        `  부서 불일치: ${misplaced.join(', ') || '없음'}\n` +
        `  중복: ${[...new Set(duplicated)].join(', ') || '없음'}\n` +
        `  ${toRepoRelative(CONSOLE_SAMPLE_PATH)} 의 sampleAgents 를 맞추세요 — 표본이 실제 인원을 재현해야 자리 부족·이름표 겹침이 검사에 걸립니다.`,
    );
  }
}

// ──────────────────────────── 그룹 분류 ────────────────────────────

/**
 * 접두사 → 섹션 라벨. 위에서부터 첫 일치, 미일치는 `기타`.
 * 키 이름 자체로만 판정한다(과거엔 첫 규칙이 `required` 라 필수 SLACK_* 키가 생기면
 * Slack 이 아니라 인프라로 분류되는 구조였다).
 */
const ENV_GROUP_RULES: ReadonlyArray<readonly [RegExp, string]> = [
  [/^(PORT$|REDIS_|DATABASE_URL$)/u, '인프라 (앱 부팅 필수)'],
  [/^SLACK_/u, 'Slack'],
  [/^NOTION_/u, 'Notion'],
  [/^(WEBHOOK_SECRET$|GITHUB_WEBHOOK)/u, 'Webhook'],
  [/^GITHUB_/u, 'GitHub'],
  [/^AUTOPILOT_/u, 'Autopilot cron'],
  [/^(CLAUDE_|ANTHROPIC_)/u, 'LLM CLI 인증'],
  [/^BE_(SANDBOX|AUTONOMOUS)/u, 'BE 자율개발'],
  [/^(IMPACT_REPORT_|PR_CAREERLOG_|CAREER_LOG_)/u, 'careerLog / Impact'],
  [/^(CAREER_|RESUME_|JOB_APPLICATION_)/u, 'Career Mate'],
  [/^PR_REVIEW_/u, 'PR 리뷰 루프'],
  [/^DOCS_AUDIT_/u, 'docs-sync-audit'],
  [/^(BLOG_|EVENING_RETRO_)/u, '블로그 / 저녁 발행'],
  [
    /^(SUBCONSCIOUS_|EPISODIC_|PREFERENCE_|HUMANIZE_)/u,
    'proactive / 메모리 / 윤문',
  ],
  [/^CONSOLE_/u, '콘솔 리모컨'],
  [/^(TOSS_|STOCK_)/u, '주식 모니터링'],
];

const ENV_GROUP_FALLBACK = '기타';

/** 섹션 출력 순서 — 규칙 선언 순서 + 마지막에 기타. */
const ENV_GROUP_ORDER: readonly string[] = [
  ...new Set(ENV_GROUP_RULES.map(([, label]) => label)),
  ENV_GROUP_FALLBACK,
];

function groupEnvEntries(
  entries: readonly EnvEntry[],
): Map<string, EnvEntry[]> {
  const buckets = new Map<string, EnvEntry[]>();
  for (const entry of entries) {
    const rule = ENV_GROUP_RULES.find(([pattern]) => pattern.test(entry.name));
    const label = rule ? rule[1] : ENV_GROUP_FALLBACK;
    const bucket = buckets.get(label) ?? [];
    bucket.push(entry);
    buckets.set(label, bucket);
  }
  return buckets;
}

// ──────────────────────────── 렌더링 ────────────────────────────

function escapeCell(text: string): string {
  return text.replace(/\|/gu, '\\|');
}

function renderAgentCatalog(): string {
  const rows = [...AGENT_REGISTRY]
    .sort((a, b) => a.displayName.localeCompare(b.displayName))
    .map((entry) => {
      const slash = entry.slashCommands.length
        ? entry.slashCommands.map((command) => `\`${command}\``).join(', ')
        : '— (webhook/자동)';
      const model = AGENT_TO_PROVIDER[entry.agentType];
      return `| ${escapeCell(entry.displayName)} | \`${entry.agentType}\` | ${slash} | ${model} | \`${escapeCell(entry.usecasePath)}\` | ${escapeCell(entry.description)} |`;
    });

  return [
    GENERATED_BANNER,
    '',
    '# 에이전트 카탈로그',
    '',
    `이대리의 에이전트 ${AGENT_REGISTRY.length}종. SoT: \`src/agent-registry/agent-registry.ts\` + \`AGENT_TO_PROVIDER\`(\`src/model-router/domain/agent-provider.map.ts\`).`,
    '드리프트는 `pnpm docs:check` 가 차단하고, agentType 집합 정합성은 `agent-registry.spec.ts` 가 강제한다.',
    '',
    '| 에이전트 | AgentType | 슬래시 | 모델 | 진입 usecase | 설명 |',
    '|---|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

function renderEnvCatalog(): string {
  const entries = parseEnvEntries();
  assertEnvEntries(entries);

  const buckets = groupEnvEntries(entries);
  const sections: string[] = [];

  for (const label of ENV_GROUP_ORDER) {
    const groupEntries = buckets.get(label);
    if (!groupEntries || groupEntries.length === 0) {
      continue;
    }
    const rows = groupEntries.map(
      (entry) =>
        `| \`${entry.name}\` | ${entry.required ? '✅' : '❌'} | ${escapeCell(entry.description) || '—'} |`,
    );
    sections.push(
      `## ${label}`,
      '',
      '| 키 | 필수 | 설명 |',
      '|---|---|---|',
      ...rows,
      '',
    );
  }

  return [
    GENERATED_BANNER,
    '',
    '# 환경변수 카탈로그',
    '',
    `SoT: \`src/config/app.config.ts\` 의 \`EnvironmentVariables\` (class-validator). 총 ${entries.length}개.`,
    '설명은 각 변수 주석의 첫 문장 발췌 — 상세는 app.config.ts 주석 참조. `.env.example` 동기는 `pnpm check:env`.',
    '',
    ...sections,
  ].join('\n');
}

// ──────────────────────────── main ────────────────────────────

const TARGETS: ReadonlyArray<{ path: string; render: () => string }> = [
  { path: AGENT_CATALOG_PATH, render: renderAgentCatalog },
  { path: ENV_CATALOG_PATH, render: renderEnvCatalog },
];

function toRepoRelative(absolutePath: string): string {
  return absolutePath.replace(`${REPO_ROOT}/`, '');
}

function main(): void {
  const checkMode = process.argv.includes('--check');
  const drifted: string[] = [];

  // 생성물 비교보다 먼저 본다 — 이 계약은 문서가 아니라 화면이 깨지는 문제라,
  // 카탈로그가 동기 상태여도 통과시키면 안 된다.
  assertConsoleAgentSync();

  for (const target of TARGETS) {
    const expected = target.render();
    if (checkMode) {
      const actual = existsSync(target.path)
        ? readFileSync(target.path, 'utf8')
        : '';
      if (actual !== expected) {
        drifted.push(target.path);
      }
    } else {
      writeFileSync(target.path, expected);
    }
  }

  if (checkMode) {
    if (drifted.length > 0) {
      console.error(
        '[sync-docs] FAIL: 생성 문서가 코드와 어긋났습니다(드리프트):',
      );
      for (const path of drifted) {
        console.error(`  - ${toRepoRelative(path)}`);
      }
      console.error('\n수정: `pnpm docs:sync` 실행 후 변경분을 커밋하세요.');
      process.exitCode = 1;
      return;
    }
    console.log('[sync-docs] OK — 생성 문서가 코드와 동기 상태입니다.');
    return;
  }

  console.log(
    `[sync-docs] 생성 완료: ${TARGETS.map((target) => toRepoRelative(target.path)).join(', ')}`,
  );
}

main();
