/**
 * sync-docs — docs-as-code 생성기 + 드리프트 게이트
 *
 * 코드의 단일 소스(SoT)에서 머신-정확한 레퍼런스 카탈로그를 생성한다.
 * sbe-slack-bot 의 sync-docs(.cjs) 패턴을 이 레포에 맞게 이식한 것.
 *
 * 생성 대상 (둘 다 전체가 생성물 — 수동 편집 금지):
 *   - docs/agent-catalog.md  ← AGENT_REGISTRY(import) + AGENT_TO_PROVIDER(텍스트 파싱)
 *   - docs/env-catalog.md    ← src/config/app.config.ts (텍스트 파싱: 이름/필수/설명/그룹)
 *
 * 손으로 큐레이션된 README 는 일부러 덮지 않는다(발췌·그룹핑이 생성 덤프보다 낫다).
 * README 는 위 두 카탈로그를 링크로 가리킨다.
 *
 * 모드:
 *   ts-node scripts/sync-docs.ts           # 카탈로그 재생성(쓰기)  → pnpm docs:sync
 *   ts-node scripts/sync-docs.ts --check   # 드리프트 시 exit 1     → pnpm docs:check
 *
 * `.env.example` 동기는 본 생성기 범위 밖 — scripts/check-env-sync.cjs(pnpm check:env) 가 담당.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { AGENT_REGISTRY } from '../src/agent-registry/agent-registry';

const REPO_ROOT = resolve(__dirname, '..');
const APP_CONFIG_PATH = join(REPO_ROOT, 'src', 'config', 'app.config.ts');
const MODEL_ROUTER_PATH = join(
  REPO_ROOT,
  'src',
  'model-router',
  'application',
  'model-router.usecase.ts',
);
const AGENT_CATALOG_PATH = join(REPO_ROOT, 'docs', 'agent-catalog.md');
const ENV_CATALOG_PATH = join(REPO_ROOT, 'docs', 'env-catalog.md');

const GENERATED_BANNER =
  '<!-- AUTO-GENERATED by scripts/sync-docs.ts — 직접 편집하지 마세요. `pnpm docs:sync` 로 갱신. -->';

// ──────────────────────────── 파서 ────────────────────────────

/** model-router.usecase.ts 의 AGENT_TO_PROVIDER → { [agentType]: model } */
function parseAgentModels(): Record<string, string> {
  const text = readFileSync(MODEL_ROUTER_PATH, 'utf8');
  const map: Record<string, string> = {};
  const pattern = /\[AgentType\.(\w+)\]:\s*ModelProviderName\.(\w+)/gu;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(text)) !== null) {
    map[match[1]] = match[2];
  }
  return map;
}

interface EnvEntry {
  name: string;
  required: boolean;
  description: string;
}

/**
 * app.config.ts → env 항목.
 * @IsOptional 유무로 required 판정, 속성 직전 contiguous `//` 블록의 첫 줄을 설명으로.
 */
function parseEnvEntries(): EnvEntry[] {
  const lines = readFileSync(APP_CONFIG_PATH, 'utf8').split(/\r?\n/u);
  const entries: EnvEntry[] = [];
  let optionalFlag = false;
  let commentBuffer: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();

    if (line.startsWith('//')) {
      commentBuffer.push(line.replace(/^\/\/\s?/u, '').trim());
      continue;
    }
    if (line.startsWith('@IsOptional')) {
      optionalFlag = true;
      continue;
    }
    if (line.startsWith('@')) {
      // 다른 데코레이터 — 주석 버퍼는 유지(설명은 데코레이터 위에 있음).
      continue;
    }

    const propertyMatch = raw.match(/^\s+([A-Z][A-Z0-9_]+)[?!]?\s*:/u);
    if (propertyMatch) {
      entries.push({
        name: propertyMatch[1],
        required: !optionalFlag,
        description: commentBuffer[0] ?? '',
      });
      optionalFlag = false;
      commentBuffer = [];
      continue;
    }

    // 빈 줄 = 속성 블록 경계 → stale 주석 버퍼 리셋. 데코레이터 인자의 multi-line
    // 본문(예: @Matches({ message: ... }))은 비-빈 줄이라 리셋하지 않아, 주석이 속성까지 살아남는다.
    if (line.length === 0) {
      commentBuffer = [];
    }
  }
  return entries;
}

// ──────────────────────────── 그룹 분류 ────────────────────────────

const ENV_GROUPS: ReadonlyArray<{
  label: string;
  match: (e: EnvEntry) => boolean;
}> = [
  { label: '인프라 (앱 부팅 필수)', match: (e) => e.required },
  { label: 'Slack', match: (e) => e.name.startsWith('SLACK_') },
  { label: 'Notion', match: (e) => e.name.startsWith('NOTION_') },
  {
    label: 'Webhook',
    match: (e) =>
      e.name === 'WEBHOOK_SECRET' || e.name.startsWith('GITHUB_WEBHOOK'),
  },
  {
    label: 'Cron 자동 발화',
    match: (e) =>
      /^(MORNING_BRIEFING|WEEKLY_SUMMARY|DAILY_EVAL|CEO_META_CRON|IMPACT_REPORT_RECENT)_/u.test(
        e.name,
      ),
  },
  {
    label: 'Claude / LLM',
    match: (e) => /^(CLAUDE_|ANTHROPIC_)/u.test(e.name),
  },
  { label: 'GitHub', match: (e) => e.name.startsWith('GITHUB_') },
  {
    label: 'careerLog / Impact',
    match: (e) =>
      /(CAREER_LOG|PR_CAREERLOG|IMPACT_REPORT_GITHUB)/u.test(e.name),
  },
  {
    label: 'BE 자율개발',
    match: (e) => /^BE_(SANDBOX|AUTONOMOUS)/u.test(e.name),
  },
  { label: '기타', match: () => true },
];

function groupOf(entry: EnvEntry): string {
  return ENV_GROUPS.find((group) => group.match(entry))!.label;
}

// ──────────────────────────── 렌더링 ────────────────────────────

function escapeCell(text: string): string {
  return text.replace(/\|/gu, '\\|');
}

function renderAgentCatalog(): string {
  const models = parseAgentModels();
  const rows = [...AGENT_REGISTRY]
    .sort((a, b) => a.displayName.localeCompare(b.displayName))
    .map((entry) => {
      const slash = entry.slashCommands.length
        ? entry.slashCommands.map((s) => `\`${s}\``).join(', ')
        : '— (webhook/자동)';
      const model = models[entry.agentType] ?? '?';
      return `| ${escapeCell(entry.displayName)} | \`${entry.agentType}\` | ${slash} | ${model} | \`${escapeCell(entry.usecasePath)}\` | ${escapeCell(entry.description)} |`;
    });

  return [
    GENERATED_BANNER,
    '',
    '# 에이전트 카탈로그',
    '',
    `이대리의 에이전트 ${AGENT_REGISTRY.length}종. SoT: \`src/agent-registry/agent-registry.ts\` + \`AGENT_TO_PROVIDER\`(\`model-router.usecase.ts\`).`,
    '드리프트는 `pnpm docs:check` 가 차단하고, agentType 집합 정합성은 `agent-registry.spec.ts` 가 강제한다.',
    '',
    '| 에이전트 | AgentType | 슬래시 | 모델 | 진입 usecase | 설명 |',
    '|---|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

function renderEnvCatalog(): string {
  const entries = parseEnvEntries();
  const sections: string[] = [];

  for (const { label } of ENV_GROUPS) {
    const groupEntries = entries.filter((entry) => groupOf(entry) === label);
    if (groupEntries.length === 0) {
      continue;
    }
    const rows = groupEntries.map(
      (entry) =>
        `| \`${entry.name}\` | ${entry.required ? '✅' : '❌'} | ${escapeCell(entry.description) || '—'} |`,
    );
    sections.push(
      `## ${label}`,
      '',
      '| 키 | 필수 | 설명 |',
      '|---|---|---|',
      ...rows,
      '',
    );
  }

  return [
    GENERATED_BANNER,
    '',
    '# 환경변수 카탈로그',
    '',
    `SoT: \`src/config/app.config.ts\` 의 \`EnvironmentVariables\` (class-validator). 총 ${entries.length}개.`,
    '설명은 각 변수의 첫 주석 줄 발췌 — 상세는 app.config.ts 주석 참조. `.env.example` 동기는 `pnpm check:env`.',
    '',
    ...sections,
  ].join('\n');
}

// ──────────────────────────── main ────────────────────────────

const TARGETS: ReadonlyArray<{ path: string; render: () => string }> = [
  { path: AGENT_CATALOG_PATH, render: renderAgentCatalog },
  { path: ENV_CATALOG_PATH, render: renderEnvCatalog },
];

function main(): void {
  const checkMode = process.argv.includes('--check');
  const drifted: string[] = [];

  for (const target of TARGETS) {
    const expected = target.render();
    if (checkMode) {
      const actual = existsSync(target.path)
        ? readFileSync(target.path, 'utf8')
        : '';
      if (actual !== expected) {
        drifted.push(target.path);
      }
    } else {
      writeFileSync(target.path, expected);
    }
  }

  const relative = (p: string): string => p.replace(`${REPO_ROOT}/`, '');

  if (checkMode) {
    if (drifted.length > 0) {
      console.error(
        '[sync-docs] FAIL: 생성 문서가 코드와 어긋났습니다(드리프트):',
      );
      for (const path of drifted) {
        console.error(`  - ${relative(path)}`);
      }
      console.error('\n수정: `pnpm docs:sync` 실행 후 변경분을 커밋하세요.');
      process.exitCode = 1;
      return;
    }
    console.log('[sync-docs] OK — 생성 문서가 코드와 동기 상태입니다.');
    return;
  }

  console.log(
    `[sync-docs] 생성 완료: ${TARGETS.map((t) => relative(t.path)).join(', ')}`,
  );
}

main();
