export enum VacationErrorCode {
  HIRE_DATE_NOT_CONFIGURED = 'VACATION_HIRE_DATE_NOT_CONFIGURED',
  INVALID_DATE_RANGE = 'VACATION_INVALID_DATE_RANGE',
  INVALID_COMMAND = 'VACATION_INVALID_COMMAND',
  USAGE_NOT_FOUND = 'VACATION_USAGE_NOT_FOUND',
  NL_PARSE_FAILED = 'VACATION_NL_PARSE_FAILED',
}
