export enum PoShadowErrorCode {
  NO_RECENT_PLAN = 'PO_SHADOW_NO_RECENT_PLAN',
  STALE_PLAN = 'PO_SHADOW_STALE_PLAN',
  INVALID_MODEL_OUTPUT = 'PO_SHADOW_INVALID_MODEL_OUTPUT',
  // 확인 카드를 눌렀을 때 목표가 저장 조건(달성 기준·활성 상한)을 어겼다.
  PRODUCT_GOAL_REJECTED = 'PO_SHADOW_PRODUCT_GOAL_REJECTED',
  INVALID_PRODUCT_GOAL_PAYLOAD = 'PO_SHADOW_INVALID_PRODUCT_GOAL_PAYLOAD',
}
