export enum CareerMateErrorCode {
  NL_PARSE_FAILED = 'CAREER_MATE_NL_PARSE_FAILED',
  NO_EVIDENCE = 'CAREER_MATE_NO_EVIDENCE',
  INVALID_MODEL_OUTPUT = 'CAREER_MATE_INVALID_MODEL_OUTPUT',
  CONFIG_MISSING = 'CAREER_MATE_CONFIG_MISSING',
  JD_EMPTY = 'CAREER_MATE_JD_EMPTY',
}
